version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: task-management-api-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: task-management-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678